### ISSUE TITLE
support for nextJs

### ISSUE THREAD

**Issue by hebertdev** [jaywcjlove/react-monacoeditor#114]
I think that the css files are not allowed to be imported from next.js they could give a compiled version of these.

https://nextjs.org/docs/messages/css-npm

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-md-editor/issues/446#issue-1417594634

Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js  
Example: [@uiwjs/next-remove-imports/example](https://github.com/uiwjs/next-remove-imports/tree/main/example)  
Example: https://next-remove-imports-example.vercel.app
