### ISSUE TITLE
Add typescript types

### ISSUE THREAD

**Issue by Arthur-Kamau** [jaywcjlove/react-monacoeditor#15]
This plugin is awesome .Thanks.
Small problem though trying to use it within typescript causes an error as it does not have typescript types.
Thanks.

**Comment by jaywcjlove** [comment]
@Arthur-Kamau Upgrade `@uiw/react-monacoeditor@2.2.0`

**Comment by worrel** [comment]
Hi @jaywcjlove this is useful but the `typings/index.d.ts` folder does not appear to be included in the package when installed in `node_modules` so Typescript still doesn't find them:

<img width="703" alt="Screen Shot 2020-09-04 at 10 00 53 AM" src="https://user-images.githubusercontent.com/976935/92247682-8bba4680-ee95-11ea-9876-2fd409f75892.png">

I got it working by manually copying the type definitions into a folder that I've specified in tsconfig.json `typeRoots`

**Comment by jaywcjlove** [comment]
@worrel thx! Upgrade `+ @uiw/react-monacoeditor@2.2.2`
