### ISSUE TITLE
Importing with browserify?

### ISSUE THREAD

**Issue by pierznj** [jaywcjlove/react-monacoeditor#63]
Looks like a great project, and exactly what I'm looking for. Unfortunately, when I try to import the component, my gulp/browserify build process fails with:

`Error: Cannot find module 'monaco-editor' from '/<project path>/node_modules/@uiw/react-monacoeditor/lib/cjs'`

I note that for webpack, a webpack plug in is required. Can it work with browserify?

**Comment by jaywcjlove** [comment]
@pierznj Not sure if it can be used in browserify.



Dependencies on [monaco-editor](https://www.npmjs.com/package/monaco-editor).

do I need to install it?

**Comment by pierznj** [comment]
I believe you're right. There's probably some dirty way to do it, but I'm going to try Ace instead. Thanks for replying.
